### ISSUE TITLE
Point mechanism remains infinitely recursive

### ISSUE THREAD

**Issue by Viterbo** [vapaee/vapaee-smart-contracts#37]
**type:**
bugfix request

**problem:**
The intention is for users to level up kyc by having more witnesses and at the same time witnessing other users to help them level up. However, this approach has the problem that two users can promote each other infinitely.

**solution:**
When counting the points of a link, the sum of the raw points should not be taken into account, but the logarithm of that number instead. This would prevent a user's points from serving to raise the level of their own token and generate an infinite recursive effect.

**code:**
Create new attribute called _kyclevel_ ([near point](https://github.com/vapaee/vapaee-smart-contracts/blob/dev/include/vapaee/tprofile/tables/links.hpp#L17)) in links table. When updating the [link points](https://github.com/vapaee/vapaee-smart-contracts/blob/dev/include/vapaee/tprofile/modules/link.hpp#L191), it also should be calculated the kyclevel as
```c++
row.points = link_points;
row.kyclevel = floor(log2(row.points));
```
Take the link.kyclevel of the link to calculate profile.kyclevel [instead of link.points](https://github.com/vapaee/vapaee-smart-contracts/blob/dev/include/vapaee/tprofile/modules/prof.hpp#L81).
```c++
for(auto link_it : link_table)
    profile_totals[link_it.platform_id] = link_it.kyclevel;
```

**Comment by Viterbo** [comment]
Just for the record, this bug was pointed out by @guilledk at the time but sadly was dismissed. Sorry for that :(

**Comment by guilledk** [comment]
No worries wasn't dismissed just put on hold :wink:

**Comment by Viterbo** [comment]
This fix is deprecated. We are going to implement multilevel KYC in another contract
