### ISSUE TITLE
koinonospool

### ISSUE THREAD

**Issue by Viterbo** [vapaee/vapaee-smart-contracts#46]
We need to implement **asap** a specific contract for specific functionality, which later will become just a case of a new protocol.

We need the contract to mimic a pool converter of the bancor protocol but with the following differences:

- **no fees**: no fees will be charged on swaps
- **private liquidity**: only admin can add or remove liquidity
- **no caller restrictions**: anyone can transfer to this contract using bancor protocol.

We need to be able to create two pools:

- TIPS/**EUROT**
- KOINE/**EUROT**

The three tokens are implemented in [vapaeetokens](https://telos.bloks.io/account/vapaeetokens?loadContract=true&tab=Tables&table=stat&account=vapaeetokens&scope=EUROT&limit=100).

**Comment by guilledk** [comment]
Discussing it a bit further in the development chat, we agreed on the following tasks:

Create a pool to swap tokens A & B:
- [x] Admin can add liquidity to the pool
- [x] Send transactions to pool with the following memo protocol:
     - Empty: fail, memo mustn't be empty
     - `skip`: no processing
     - `<version>,<path>,<min>,<recipient>`: *bancor.v1* protocol
        In this case the path will always have at least one step which consists of the pair `<pool name> <token>`.
        `pool name` is the name of the pool contract, and `token` has to be a token available on that pool, and must be opposite of the token being transferred.
        The exchange rate will be determined purely by liquidity ratio of one by the other.
        Before sending the tokens we verify the total exchanged amount is bigger than `min`, and finally send the result to `recipient`.
