### ISSUE TITLE
telospooldex

### ISSUE THREAD

**Issue by Viterbo** [vapaee/vapaee-smart-contracts#47]
Telos Pool DEX will complement the book DEX functionality of Telos DEX with a swap pool for every market. This contract will implement the converter role of the bancor protocol and anyone can create any pool, as well as adding and removing liquidity.

#### Features:
- **bancor protocol**: can receive a simple transfer with a memo [holding instructions for a swap](https://github.com/guilledk/bancor-protocol/blob/custom_translation/contracts/BancorConverter/src/convert.cpp#L8). Must respect v1 of bancor protocol.
- **fees**: all pools created with this contract will share the same fee percentage. This number will be [declared](https://github.com/vapaee/vapaee-smart-contracts/blob/dev/include/vapaee/dex/modules/dao.hpp#L464) in **telosbookdex** and managed by [Telos Decide](https://github.com/vapaee/vapaee-smart-contracts/blob/dev/include/vapaee/dex/modules/dao.hpp#L448). 
- **markets**: any user can create any pool if it does not exist but the market does or can be created. It must [respect currencies and token groups](https://github.com/vapaee/vapaee-smart-contracts/blob/dev/include/vapaee/dex/modules/market.hpp#L129) of **telosbookdex**.
- **free caller**: it must be no restrictions on who can "call" (transfer) the swap functionality. It should not be restricted to a specific router. 
- **liquidity**: anyone can contribute to any pool's liquidity. 

#### How liquidity reward works
Every time a user adds liquidity to a specific pool, he or she gains points on this pool. These points represent the participation of the user in the pool and happen to be the same percentage: the user participation over the total participation and the user liquidity added over the total liquidity.

Then every time any other user swaps tokens using this pool is charged with a fee. The amount charged is split in half, only one half is swapped, and then these two parts stay in the pool's liquidity but not changing anyone's participation. This creates an increase in liquidity without changing percentages. Meaning that now every liquidity provider can withdraw their contribution and will get more than was added in the first place.

**Comment by guilledk** [comment]
Closed by #53
